name: CI

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore ./GardeningApi/GardeningApi.sln

      - name: Build
        run: dotnet build ./GardeningApi/GardeningApi.sln

      - name: Test with the dotnet CLI
        run: dotnet test ./GardeningApi/GardeningApi.sln

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@2.1.0 # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/sonarcloud-scan
        with:
          projectBaseDir: ./GardeningApi/
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
